# Generated by Django 2.1.4 on 2018-12-28 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KeyPair',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pubkey', models.TextField()),
                ('privkey', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.TextField()),
                ('recepient', models.TextField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('inputs', models.TextField()),
                ('sender_output', models.TextField()),
                ('recepient_output', models.TextField()),
                ('hash', models.TextField()),
                ('signature', models.TextField()),
            ],
        ),
    ]
