# Generated by Django 2.1.4 on 2018-12-29 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pubkey', models.TextField()),
                ('utxos', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='recepient_output',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='sender_output',
        ),
        migrations.AddField(
            model_name='transaction',
            name='outputs',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='hash',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='signature',
            field=models.TextField(null=True),
        ),
    ]
