# Generated by Django 2.1.4 on 2018-12-30 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_node_nodeinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='nodeinfo',
            name='miner_pid',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='used',
            field=models.BooleanField(default=False),
        ),
    ]
